### ISSUE TITLE
Missing Docker image?

### ISSUE THREAD

**Issue by simplesteph** [codesuki/ecs-gen#7]
It seems the docker image hasn't been published to docker hub?

**Comment by codesuki** [comment]
Hi there. If I remember correctly I only publish https://github.com/codesuki/ecs-nginx-proxy as a Docker image because using only `ecs-gen` as a standalone thing doesn't seem to make so much sense. Maybe it does and I am just missing it (extending the docker image maybe?).
Do you think it's worthwhile to publish it? Then I will consider it.

**Comment by simplesteph** [comment]
@codesuki well I just thought about trying that command line manually or something. Ideally just see the output logged or something without having the ecs-nginx-proxy run in my ecs cluster first. 

And I was asking this question because your doc suggests a Docker image exists: https://github.com/codesuki/ecs-gen#docker

**Comment by codesuki** [comment]
True! That must have slipped my mind. 
Here you go: https://hub.docker.com/r/codesuki/ecs-gen/

Should be built in a few mins.

**Comment by codesuki** [comment]
Had to change the Dockerfile. Now it's up!
